# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kidnapped Robot
tagline:          'Attempting Relocalization'
description:      'Ramblings of a mechanical engineer turned roboticist turned computer vision expert turned machine learning ... guy.'
url:              https://safijari.github.io
baseurl:          /

author:
  name:           'Jariullah Safi'
  url:            https://twitter.com/safijari

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
