# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            The Kidnapped Robot
tagline:          'Attempting Relocalization'
description:      'Ramblings of a mechanical engineer turned roboticist turned computer vision expert turned machine learning errr ... guy.'
url:              https://safijari.github.io/
baseurl:          /

author:
  name:           'Jariullah Safi'
  url:            https://twitter.com/safijari

paginate:         5

# Custom vars
plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
 - jekyll-paginate

disqus: kidnappedrobot

google_analytics: UA-85264522-1
